# Generated by Django 6.0.2 on 2026-02-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='study_destination',
            new_name='destination',
        ),
    ]
