# Generated by Django 6.0.2 on 2026-02-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_fix_duplicate_destination_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="application",
            name="completion_year",
            field=models.IntegerField(default=2020, help_text="Year of completion"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="english_score",
            field=models.CharField(
                blank=True, help_text="e.g., IELTS 6.5 bands, TOEFL 90", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="english_test",
            field=models.CharField(
                choices=[
                    ("IELTS", "IELTS"),
                    ("TOEFL", "TOEFL"),
                    ("PTE", "PTE Academic"),
                    ("DUOLINGO", "Duolingo English Test"),
                    ("CAMBRIDGE", "Cambridge English"),
                    ("NONE", "No English Test Taken"),
                    ("OTHER", "Other"),
                ],
                default="NONE",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="full_name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="grade_marks",
            field=models.CharField(
                default=1, help_text="e.g., 85%, GPA 3.5/4.0", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="last_qualification",
            field=models.CharField(
                default=1,
                help_text="e.g., Bachelor's in Computer Science",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="phone_number",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="preferred_course",
            field=models.CharField(
                default=1, help_text="e.g., MS in Computer Science", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="application",
            name="visa_refusal",
            field=models.BooleanField(
                default=False, help_text="Any previous visa refusal?"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="visa_refusal_details",
            field=models.TextField(blank=True, help_text="If yes, provide details"),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("PASSPORT", "Passport"),
                    ("PHOTO", "Photograph"),
                    ("BANK_STATEMENT", "Bank Statement"),
                    ("EMPLOYMENT_LETTER", "Employment Letter"),
                    ("INVITATION_LETTER", "Invitation Letter"),
                    ("EDUCATION_CERTIFICATE", "Education Certificate"),
                    ("TRANSCRIPT", "Academic Transcript"),
                    ("ENGLISH_TEST", "English Test Result"),
                    ("POLICE_CLEARANCE", "Police Clearance"),
                    ("MEDICAL_REPORT", "Medical Report"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
